# ------------------------------------------------------------
# Run every day at 6pm CST (Cutoff for traffic views 0:00 UTC)

#schedules:
#- cron: "0 18 * * *"
#  displayName: Daily Build and Run
#  branches:
#    include:
#   - master

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# ----------------------
# Restore Nuget Packages

- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# --------------
# Replace Tokens

- task: replacetokens@5
  inputs:
    targetFiles: '**/*.config'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

# --------------
# Build Solution

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:Platform="$(buildPlatform)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# ---------------------
# Copy Files to Staging

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(buildConfiguration)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'

# -----------------
# Publish Artifacts

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'
    publishLocation: 'Container'
